---
- name: PBS | Add Proxmox repository GPG key
  ansible.builtin.get_url:
    url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ proxmox_debian_release }}.gpg"
    dest: "/etc/apt/trusted.gpg.d/proxmox-release-{{ proxmox_debian_release }}.gpg"
    mode: "0644"

- name: PBS | Add no-subscription repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pbs {{ proxmox_debian_release }} pbs-no-subscription"
    filename: pbs
    state: present

- name: PBS | Remove enterprise repository if present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pbs-enterprise.list
    state: absent

- name: PBS | Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: PBS | Install Proxmox Backup Server
  ansible.builtin.apt:
    name: proxmox-backup-server
    state: present

- name: PBS | Enable and start PBS service
  ansible.builtin.service:
    name: proxmox-backup
    enabled: true
    state: started
