---
- name: OS | System Base and Access
  import_tasks: system.yml
  tags: [system]

- name: PVE | Storage Configuration
  import_tasks: storage.yml
  tags: [storage]

- name: Security | Networking and Hardening
  import_tasks: network.yml
  tags: [network]

- name: API | Terraform configuration
  import_tasks: terraform.yml
  tags: [terraform]

- name: API | Packer configuration
  import_tasks: packer.yml
  tags: [packer]