---
- name: AMP | Install
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: AMP | Firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: [firewall]

- name: AMP | Configure ADS controller
  ansible.builtin.import_tasks: configure_ads.yml
  when: inventory_hostname in groups['amp_ads']
  tags: [configure]

- name: AMP | Configure target node
  ansible.builtin.import_tasks: configure_target.yml
  when: inventory_hostname in groups['amp_targets']
  tags: [configure]

- name: AMP | Configure OIDC
  ansible.builtin.import_tasks: oidc.yml
  when: inventory_hostname in groups['amp_ads']
  tags: [oidc]

- name: AMP | Mount NFS game data
  ansible.builtin.import_tasks: nfs_mount.yml
  when: inventory_hostname in groups['amp_targets']
  tags: [nfs]
