---
- name: OIDC | Get client secret from SSM
  ansible.builtin.set_fact:
    _amp_oidc_secret: "{{ lookup('amazon.aws.ssm_parameter', amp_ssm_oidc_client_secret, profile=aws_profile, region=aws_region) }}"
  no_log: true

- name: OIDC | Configure OIDC for ADS controller
  when: inventory_hostname in groups['amp_ads']
  block:
    - name: OIDC | ADS - Stop ADS01
      ansible.builtin.shell:
        cmd: "su -l amp -c '/opt/cubecoders/amp/ampinstmgr stop ADS01'"
      failed_when: false
      changed_when: true

    - name: OIDC | ADS - Configure OIDC settings
      ansible.builtin.lineinfile:
        path: "/home/amp/.ampdata/instances/ADS01/AMPConfig.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: true
        owner: amp
        group: amp
        mode: "0644"
      loop:
        - { regexp: "^Login[.]UseOIDC=", line: "Login.UseOIDC=True" }
        - { regexp: "^Login[.]OIDCProviderFriendlyName=", line: "Login.OIDCProviderFriendlyName=Authentik" }
        - { regexp: "^Login[.]OIDCRedirectUri=", line: "Login.OIDCRedirectUri=https://{{ amp_domain }}/" }
        - { regexp: "^Login[.]OIDCAuthorizeEndpoint=", line: "Login.OIDCAuthorizeEndpoint=https://{{ svc_authentik_domain }}/application/o/authorize/" }
        - { regexp: "^Login[.]OIDCTokenEndpoint=", line: "Login.OIDCTokenEndpoint=https://{{ svc_authentik_domain }}/application/o/token/" }
        - { regexp: "^Login[.]OIDCUserInfoEndpoint=", line: "Login.OIDCUserInfoEndpoint=https://{{ svc_authentik_domain }}/application/o/userinfo/" }
        - { regexp: "^Login[.]OIDCValidationEndpoint=", line: "Login.OIDCValidationEndpoint=https://{{ svc_authentik_domain }}/application/o/introspect/" }
        - { regexp: "^Login[.]OIDCLogoutEndpoint=", line: "Login.OIDCLogoutEndpoint=https://{{ svc_authentik_domain }}/application/o/amp/end-session/" }
        - { regexp: "^Login[.]OIDCUsernameClaim=", line: "Login.OIDCUsernameClaim=preferred_username" }
        - { regexp: "^Login[.]OIDCClientID=", line: "Login.OIDCClientID=amp" }
        - { regexp: "^Login[.]OIDCClientSecret=", line: "Login.OIDCClientSecret={{ _amp_oidc_secret }}" }
        - { regexp: "^Login[.]OIDCRoleNamePrefix=", line: "Login.OIDCRoleNamePrefix=AMP_" }
        - { regexp: "^Login[.]OIDCNewUsersDisabledAtCreation=", line: "Login.OIDCNewUsersDisabledAtCreation=False" }
        - { regexp: "^Login[.]AllowLoginFallback=", line: "Login.AllowLoginFallback=False" }
      no_log: true

    - name: OIDC | ADS - Start ADS01
      ansible.builtin.shell:
        cmd: "su -l amp -c '/opt/cubecoders/amp/ampinstmgr start ADS01'"
      changed_when: true

    - name: OIDC | ADS - Wait for ADS to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ amp_ads_port }}"
        delay: 10
        timeout: 120
        state: started
