---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart traefik
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ svc_dmz_compose_dir }}/traefik"
